import { FC } from 'react';

export const iconValues = [
  'application-developer',
  'automation',
  'benefit',
  'build-and-customize',
  'career-planning',
  'case-study',
  'chart-with-arrow-down',
  'chart-with-arrow-up',
  'choose-your-pricing-plan',
  'community',
  'c-suite',
  'database',
  'datasheet',
  'desktop',
  'documentation',
  'ebook',
  'explore-careers',
  'events',
  'build-and-customize',
  'career-planning',
  'case-study',
  'chart-with-arrow-down',
  'chart-with-arrow-up',
  'choose-your-pricing-plan',
  'community',
  'c-suite',
  'database',
  'datasheet',
  'desktop',
  'documentation',
  'ebook',
  'explore-careers',
  'events',
  'extend-visibility',
  'facilities-manager',
  'field-service-manager',
  'health-wellness',
  'holistic-development',
  'diamond-hand',
  'chat',
  'get-up-running',
  'happy-customer',
  'government',
  'infographic',
  'investor-relations',
  'it-leader',
  'learn',
  'life-balance',
  'lock',
  'manage',
  'mentoring-coaching',
  'microphone',
  'mobile-phone',
  'print',
  'profile',
  'product-release',
  'project-manager',
  'remote-work-allowance',
  'project',
  'router',
  'self-service',
  'see-locations',
  'service-ticket',
  'share',
  'shop',
  'strategic',
  'try-a-demo',
  'unhappy-customer',
  'unlock',
  'value',
  'volume',
  'value-case',
  'webinar',
  'whitepaper',
  'why-freshworks',
  'facebook',
  'twitter',
  'linkedin',
  'instagram',
  'youtube',
  'check',
  'google-icon',
] as const;
export type iconIds = typeof iconValues[number];

interface IconProps {
  size: number;
  id: iconIds;
}

export const Icon: FC<IconProps> = ({ id, size }) => (
  <svg width={size || 40} height={size || 40}>
    <use href={`/icons/sprites.svg#${id}`} />
  </svg>
);

export default Icon;
