import color from 'atoms/colors/colors';

const themeHierarchy = {
  primaryColor: {
    bg: 'primary-500',
    text: 'common-white',
    border: 'primary-500',
    hoverBg: 'primary-800',
    hoverText: 'common-white',
    focusShadow: color.primaryBlue[500],
    focusBorder: 'primaryBlue-700',
    disabledBg: 'primary-100',
    disabledText: 'common-white',
    disabledBorder: 'primary-600',
    variant: 'contained',
  },
  primaryColorDark: {
    bg: 'primary-500',
    text: 'common-white',
    border: 'primary-500',
    hoverBg: 'primary-800',
    hoverText: 'common-white',
    focusShadow: color.primaryBlue[500],
    focusBorder: 'primaryBlue-700',
    disabledBg: 'primary-100',
    disabledText: 'common-white',
    disabledBorder: 'primary-600',
    variant: 'contained',
  },
  secondaryColor: {
    bg: 'gray-900',
    text: 'common-white',
    border: 'primary-50',
    hoverBg: 'gray-700',
    hoverText: 'common-white',
    focusShadow: color.primaryBlue[500],
    focusBorder: 'primaryBlue-700',
    disabledBg: 'gray-100',
    disabledText: 'common-white',
    disabledBorder: 'gray-25',
    variant: 'contained',
  },
  secondaryColorDark: {
    bg: 'gray-900',
    text: 'common-white',
    border: 'primary-50',
    hoverBg: 'gray-700',
    hoverText: 'common-white',
    focusShadow: color.primaryBlue[500],
    focusBorder: 'primaryBlue-700',
    disabledBg: 'gray-100',
    disabledText: 'common-white',
    disabledBorder: 'gray-25',
    variant: 'contained',
  },
  tertiaryColor: {
    bg: 'common-transparent',
    text: 'primary-600',
    border: 'primary-600',
    hoverBg: 'primary-400',
    hoverText: 'common-white',
    focusShadow: color.primaryBlue[500],
    focusBorder: 'primaryBlue-700',
    disabledBg: 'common-transparent',
    disabledText: 'gray-300',
    disabledBorder: 'gray-200',
    variant: 'outlined',
  },
  tertiaryColorDark: {
    bg: 'common-transparent',
    text: 'primary-600',
    border: 'primary-600',
    hoverBg: 'primary-400',
    hoverText: 'common-white',
    focusShadow: color.primaryBlue[500],
    focusBorder: 'primaryBlue-700',
    disabledBg: 'common-transparent',
    disabledText: 'gray-300',
    disabledBorder: 'gray-200',
    variant: 'outlined',
  },
  tertiaryGray: {
    bg: 'common-transparent',
    text: 'gray-900',
    border: 'gray-200',
    hoverBg: 'gray-900',
    hoverText: 'common-white',
    focusShadow: color.primaryBlue[500],
    focusBorder: 'primaryBlue-700',
    disabledBg: 'common-transparent',
    disabledText: 'gray-100',
    disabledBorder: 'gray-200',
    variant: 'outlined',
  },
  tertiaryGrayDark: {
    bg: 'common-transparent',
    text: 'gray-900',
    border: 'gray-200',
    hoverBg: 'gray-900',
    hoverText: 'common-white',
    focusShadow: color.primaryBlue[500],
    focusBorder: 'primaryBlue-700',
    disabledBg: 'common-transparent',
    disabledText: 'gray-100',
    disabledBorder: 'gray-200',
    variant: 'outlined',
  },
  linkColor: {
    bg: 'common-transparent',
    text: 'primary-800',
    border: 'common-transparent',
    hoverBg: 'common-transparent',
    hoverText: 'primary-900',
    focusShadow: color.common.transparent,
    focusBorder: 'primaryBlue-700',
    disabledBg: 'common-transparent',
    disabledText: 'gray-100',
    disabledBorder: 'common-transparent',
    variant: 'text',
  },
  linkColorDark: {
    bg: 'common-transparent',
    text: 'common-white',
    border: 'common-transparent',
    hoverBg: 'common-transparent',
    hoverText: 'common-white',
    focusShadow: color.common.transparent,
    focusBorder: 'primaryBlue-700',
    disabledBg: 'common-transparent',
    disabledText: 'gray-100',
    disabledBorder: 'common-transparent',
    variant: 'text',
  },
  linkGray: {
    bg: 'common-transparent',
    text: 'gray-900',
    border: 'common-transparent',
    hoverBg: 'common-transparent',
    hoverText: 'gray-600',
    focusShadow: color.common.transparent,
    focusBorder: 'primaryBlue-700',
    disabledBg: 'common-transparent',
    disabledText: 'gray-100',
    disabledBorder: 'common-transparent',
    variant: 'text',
  },
  linkGrayDark: {
    bg: 'common-transparent',
    text: 'gray-900',
    border: 'common-transparent',
    hoverBg: 'common-transparent',
    hoverText: 'gray-600',
    focusShadow: color.common.transparent,
    focusBorder: 'primaryBlue-700',
    disabledBg: 'common-transparent',
    disabledText: 'gray-100',
    disabledBorder: 'common-transparent',
    variant: 'text',
  },
  secondaryOutline: {
    bg: 'common-transparent',
    text: 'gray-900',
    border: 'gray-900',
    hoverBg: 'common-transparent',
    hoverText: 'common-white',
    focusShadow: color.common.transparent,
    focusBorder: 'primaryBlue-700',
    disabledBg: 'common-transparent',
    disabledText: 'gray-100',
    disabledBorder: 'common-transparent',
    variant: 'outlined',
  },
  secondaryOutlineDark: {
    bg: 'common-transparent',
    text: 'common-white',
    border: 'common-white',
    hoverBg: 'common-transparent',
    hoverText: 'common-white',
    focusShadow: color.common.transparent,
    focusBorder: 'primaryBlue-700',
    disabledBg: 'common-transparent',
    disabledText: 'gray-100',
    disabledBorder: 'common-transparent',
    variant: 'outlined',
  },
} as const;

export type HierarchyDefinition = keyof typeof themeHierarchy;

export default themeHierarchy;
