import { ComponentStory } from '@storybook/react';

import { iAsset, iSys } from 'assets/mockData/emptyTypes';

import ComponentHeader from 'components/Header/Header';

const Template: ComponentStory<typeof ComponentHeader> = args => <ComponentHeader {...args} />;

export const componentHeader = Template.bind({});

componentHeader.parameters = {
  controls: {
    include: ['headerStyle'],
  },
};

componentHeader.args = {
  __typename: 'ComponentHeader',
  internalName: 'Dummy Hero',
  headerStyle: 'Global Nav',
  callToAction: {
    sys: {
      ...iSys,
      id: '6kHI9RjJGpewVdnXsPDQt',
    },
    ...iAsset,
    __typename: 'ComponentButton',
    internalName: 'Dummy Button - Header- CTA - Light',
    label: 'Free Trial',
    labelIcon: null,
    link: 'http://freshworks.com/',
    hierarchy: 'Tertiary Gray',
    size: 'large',
    startIcon: null,
    endIcon: null,
  },
  callToActionDark: {
    sys: {
      ...iSys,
      id: '6kHI9RjJGpenXsPDQt',
    },
    ...iAsset,
    __typename: 'ComponentButton',
    internalName: 'Dummy Button - Header- CTA - Dark',
    label: 'Free Trial',
    labelIcon: null,
    link: 'http://freshworks.com/',
    hierarchy: 'Dark Outline',
    size: 'large',
    startIcon: null,
    endIcon: null,
  },
  callToActionMobile: {
    sys: {
      ...iSys,
      id: '6kHI9RjJGpewVdneXsPDQt',
    },
    ...iAsset,
    __typename: 'ComponentButton',
    internalName: 'Dummy Button Heading Primary',
    label: 'Start Free Trial',
    labelIcon: null,
    link: 'http://freshworks.com/',
    hierarchy: 'Primary Color',
    size: 'Large',
    startIcon: null,
    endIcon: null,
  },
  navigationLinksCollection: {
    total: 0,
    limit: 0,
    skip: 0,
    items: [
      {
        sys: {
          ...iSys,
          id: '6kHI9RjJGpewVdneXsPDQt',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header - Products Links',
        label: 'Products',
        description: null,
        link: null,
        image: null,
        button: null,
        menuCollection: {
          total: 0,
          limit: 0,
          skip: 0,
          items: [
            {
              sys: {
                ...iSys,
                id: '6kHI9RjJGpewVdneXPDQt',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header - Products - Software',
              label: 'Software',
              description: null,
              link: null,
              image: null,
              button: {
                sys: {
                  ...iSys,
                  id: '6kH9RjJGpewVdneXsPDQt',
                },
                ...iAsset,
                __typename: 'ComponentButton',
                internalName: 'Dummy Header - View all Products',
                label: 'View all products',
                labelIcon: null,
                link: null,
                hierarchy: 'Link Color',
                size: 'Large',
                startIcon: null,
                endIcon: '>',
                rainbowHover: false,
              },
              menuCollection: {
                total: 0,
                limit: 0,
                skip: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '6kH9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Software - Freshdesk',
                    label: 'Freshdesk',
                    description: 'Customer support software',
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Software - Freshsales',
                    label: 'Freshsales',
                    description: 'Sales CRM Software',
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Software - Freshmarketer',
                    label: 'Freshmarketer',
                    description: 'Conversion Optimization Suite',
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: 'kHI9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Software - Freshteam',
                    label: 'Freshteam',
                    description: 'HR Software for growing business',
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDQ',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Software - Freshchat',
                    label: 'Freshmarketer',
                    description: 'Customer messaging software',
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: 'dfgdfg232423423sddf',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Software - Freshservice',
                    label: 'Freshservice',
                    description: 'IT service management software',
                    link: null,
                    image: null,
                    button: null,
                  },
                ],
              },
            },
            {
              sys: {
                ...iSys,
                id: '6kHI9pewVdneXsPDQt',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header - Products - Solutions',
              label: 'Solutions',
              description: null,
              link: null,
              image: null,
              button: null,
              menuCollection: {
                total: 0,
                limit: 0,
                skip: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '6JGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Solutions - Enterprise',
                    label: 'Enterprise service management',
                    description: null,
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGeXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Solutions - Industry',
                    label: 'Industry solutions',
                    description: null,
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHIpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Solutions - Direct',
                    label: 'Direct-to-consumer e-commerce',
                    description: null,
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Solutions - Conversational',
                    label: 'Conversational engagement',
                    description: null,
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Solutions - Customer relationship Management',
                    label: 'Customer Relationship Management',
                    description: null,
                    link: null,
                    image: null,
                    button: null,
                  },
                ],
              },
            },
          ],
        },
      },
      {
        sys: {
          ...iSys,
          id: '6kHI9RjJGpewVdneXsPDQt',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header - Platform Links',
        label: 'Platform',
        description: null,
        link: null,
        image: {
          sys: {
            ...iSys,
            id: '6kHI9RjJGpewVdneXsPDQt',
          },
          ...iAsset,
          __typename: 'ComponentImage',
          internalName: 'Dummy Header - Neo',
          title: 'Neo',
          image: {
            sys: {
              ...iSys,
              id: '6kHI9RjJGpewVdneXsPDQt',
            },
            ...iAsset,
            __typename: 'Asset',
            contentType: 'image/png',
            title: 'Neo',
            description: 'For usage with Dummy Header',
            url: 'https://images.ctfassets.net/bmpbi2fhxoeu/7Da2iKracH7XqcuP40YX3/b4e2e6da17c734602e1b337f4b2a4868/Image.png',
            width: 280,
            height: 161,
          },
        },
        button: null,
        menuCollection: {
          total: 0,
          limit: 0,
          skip: 0,
          items: [
            {
              sys: {
                ...iSys,
                id: '6kHI9RjJGpewVdneXsPDQt',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header - Platform - Our Platform',
              label: 'Our Platform',
              description: null,
              link: null,
              image: {
                sys: {
                  ...iSys,
                  id: '6kHI9RjJGpewVdneXsPDQt',
                },
                ...iAsset,
                __typename: 'ComponentImage',
                internalName: 'Dummy Header - Neo',
                title: 'Neo',
                image: {
                  sys: {
                    ...iSys,
                    id: '6kHI9RjJGpewVdneXsPDQt',
                  },
                  ...iAsset,
                  __typename: 'Asset',
                  contentType: 'image/png',
                  title: 'Neo',
                  description: 'For usage with Dummy Header',
                  url: 'https://images.ctfassets.net/bmpbi2fhxoeu/7Da2iKracH7XqcuP40YX3/b4e2e6da17c734602e1b337f4b2a4868/Image.png',
                  width: 280,
                  height: 161,
                },
              },
              button: null,
              menuCollection: {
                total: 0,
                limit: 0,
                skip: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Header Component - Platform - Our Platform - Freshworks neo platform',
                    label: 'Freshworks neo platform',
                    description: 'Lorem ipsum dolor sit amet',
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Header Component - Platform - Our Platform - Freshworks freddy AI',
                    label: 'Freshworks freddy AI',
                    description: 'Lorem ipsum dolor sit amet',
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Header Component - Platform - Our Platform - Key Features',
                    label: 'Key Features',
                    description: 'Lorem ipsum dolor sit amet',
                    link: null,
                    image: null,
                    button: null,
                  },
                ],
              },
            },
            {
              sys: {
                ...iSys,
                id: '6kHI9RjJGpewVdneXsPDQt',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header - Platform - Apps & Integrations',
              label: 'Apps & integrations',
              description: null,
              link: null,
              image: {
                sys: {
                  ...iSys,
                  id: '6kHI9RjJGpewVdneXsPDQt',
                },
                ...iAsset,
                __typename: 'ComponentImage',
                internalName: 'Dummy Header - Shopify',
                title: 'Klarna',
                image: {
                  sys: {
                    ...iSys,
                    id: '6kHI9RjJGpewVdneXsPDQt',
                  },
                  ...iAsset,
                  __typename: 'Asset',
                  contentType: 'image/png',
                  title: 'Shopify with Freshworks',
                  description: null,
                  url: 'https://images.ctfassets.net/bmpbi2fhxoeu/U7GmD1muZ3CtfR82OEH6c/c1001497ab7039e371529698913c34ad/Image.png',
                  width: 280,
                  height: 161,
                },
              },
              button: {
                sys: {
                  ...iSys,
                  id: '6kHI9RjJGpewVdneXsPDQt',
                },
                ...iAsset,
                __typename: 'ComponentButton',
                internalName: 'Dummy Header - View all Products and Solutions',
                label: 'View all products and solutions',
                labelIcon: null,
                link: null,
                hierarchy: 'Link Color',
                size: 'Large',
                startIcon: null,
                endIcon: '>',
                rainbowHover: false,
              },
              menuCollection: {
                total: 0,
                limit: 0,
                skip: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Platform - Apps & Integrations - Freshworks marketplace',
                    label: 'Freshworks marketplace',
                    description: 'Lorem ipsum dolor sit amet',
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Platform - Apps & Integrations - Developer Portal',
                    label: 'Developer Portal',
                    description: 'Customer support software',
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Platform - Apps & Integrations - Technical alliances',
                    label: 'Technical alliances',
                    description: 'Conversion Optimization Suite',
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Platform - Apps & Integrations - Mobile Apps',
                    label: 'Mobile Apps',
                    description: 'Customer messaging software',
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Platform - Apps & Integrations - Spotify Integration',
                    label: 'Spotify Integration',
                    description: 'Lorem ipsum dolor sit amet',
                    link: null,
                    image: null,
                    button: null,
                  },
                ],
              },
            },
          ],
        },
      },
      {
        sys: {
          ...iSys,
          id: '6kHI9RjJGpewVdneXsPDQt',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header - Resource Links',
        label: 'Resources',
        description: null,
        link: null,
        image: null,
        button: null,
        menuCollection: {
          total: 0,
          limit: 0,
          skip: 0,
          items: [
            {
              sys: {
                ...iSys,
                id: '6kHI9RjJGpewVdneXsPDQt',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header - Resources - Resources',
              label: 'Resources',
              description: null,
              link: null,
              image: null,
              button: null,
              menuCollection: {
                total: 0,
                limit: 0,
                skip: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Resources- Resources - Case Studies',
                    label: 'Case Studies',
                    description: 'Lorem ipsum dolor sit amet',
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Resources- Resources - Refresh community',
                    label: 'Refresh Community',
                    description: 'Lorem ipsum dolor sit amet',
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Resources- Resources - Refresh library',
                    label: 'Resource library',
                    description: 'Lorem ipsum dolor sit amet',
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Resources- Resources - Blog',
                    label: 'Blog',
                    description: 'Lorem ipsum dolor sit amet',
                    link: null,
                    image: null,
                    button: null,
                  },
                ],
              },
            },
            {
              sys: {
                ...iSys,
                id: '6kHI9RjJGpewVdneXsPDQt',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header - Resources - Support & services',
              label: ' Support & services',
              description: null,
              link: null,
              image: null,
              button: null,
              menuCollection: {
                total: 0,
                limit: 0,
                skip: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Resources - Support & services - Customer Support',
                    label: 'Customer Support',
                    description: null,
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Resources - Support & services - Software academy',
                    label: 'Software academy',
                    description: null,
                    link: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Resources - Support & services - Professional services',
                    label: 'Professional services',
                    description: null,
                    link: null,
                    image: null,
                    button: null,
                  },
                ],
              },
            },
            {
              sys: {
                ...iSys,
                id: '6kHI9RjJGpewVdneXsPDQt',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header- Resources - Latest stories',
              label: 'Latest stories',
              blogFormat: true,
              description: null,
              link: null,
              image: null,
              button: null,
              menuCollection: {
                total: 0,
                limit: 0,
                skip: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Resources - Latest Stories - Clarity',
                    label: 'Clarity Business Travel achieves 96% CSAT',
                    description: 'Lorem ipsum dolor sit amet',
                    link: null,
                    image: {
                      sys: {
                        ...iSys,
                        id: '6kHI9RjJGpewVdneXsPDQt',
                      },
                      ...iAsset,
                      __typename: 'ComponentImage',
                      internalName: 'Dummy Header - Multichoice',
                      title: 'Multichoice',
                      image: {
                        sys: {
                          ...iSys,
                          id: '6kHI9RjJGpewVdneXsPDQt',
                        },
                        ...iAsset,
                        __typename: 'Asset',
                        contentType: 'image/png',
                        title: 'Multichoice',
                        description: 'For usage inside Dummy Header',
                        url: 'https://images.ctfassets.net/bmpbi2fhxoeu/2MXeGFH5xKlvMC63mVcmky/679e0e5b00d3e8af9cf8806d5bacfa68/Image.png',
                        width: 280,
                        height: 161,
                      },
                    },
                    button: {
                      sys: {
                        ...iSys,
                        id: '6kHI9RjJGpewVdneXsPDQt',
                      },
                      ...iAsset,
                      __typename: 'ComponentButton',
                      internalName: 'Dummy Header - Full Story',
                      label: 'Full Story',
                      labelIcon: null,
                      link: null,
                      hierarchy: 'Link Color',
                      size: 'Large',
                      startIcon: null,
                      endIcon: '>',
                      rainbowHover: false,
                    },
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6kHI9RjJGpewVdneXsPDQt',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Resources - Latest stories - Bridgestone',
                    label: 'Bridgestone slashes average ticket age by 97%',
                    description: 'Lorem ipsum dolor sit amet',
                    link: null,
                    image: {
                      sys: {
                        ...iSys,
                        id: '6kHI9RjJGpewVdneXsPDQt',
                      },
                      ...iAsset,
                      __typename: 'ComponentImage',
                      internalName: 'Dummy Header - Klarna',
                      title: 'Klarna',
                      image: {
                        sys: {
                          ...iSys,
                          id: '6kHI9RjJGpewVdneXsPDQt',
                        },
                        ...iAsset,
                        __typename: 'Asset',
                        contentType: 'image/png',
                        title: 'Klarna - Dummy Header',
                        description: 'For use inside Dummy header',
                        url: 'https://images.ctfassets.net/bmpbi2fhxoeu/23FAP4MUVXS62YpzrcPZe9/fa01c77d31a1f40613917455c4024f33/Image.png',
                        width: 280,
                        height: 161,
                      },
                    },
                    button: {
                      sys: {
                        ...iSys,
                        id: '6kHI9RjJGpewVdneXsPDQt',
                      },
                      ...iAsset,
                      __typename: 'ComponentButton',
                      internalName: 'Dummy Header - Full Story',
                      label: 'Full Story',
                      labelIcon: null,
                      link: null,
                      hierarchy: 'Link Color',
                      size: 'Large',
                      startIcon: null,
                      endIcon: '>',
                      rainbowHover: false,
                    },
                  },
                ],
              },
            },
          ],
        },
      },
      {
        sys: {
          ...iSys,
          id: '6kHI931Tesfrwe3123123pewVdneXsPDQt',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header - Pricing',
        label: 'Pricing',
        description: null,
        link: null,
        image: null,
        button: null,
        menuCollection: {
          total: 0,
          limit: 0,
          skip: 0,
          items: [],
        },
      },
      {
        sys: {
          ...iSys,
          id: '6kHI9RjJGpewVdneXsPDQt',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header - Demos',
        label: 'Demos',
        description: null,
        link: null,
        image: null,
        button: null,
        menuCollection: {
          total: 0,
          limit: 0,
          skip: 0,
          items: [],
        },
      },
      {
        ...iAsset,
        sys: {
          ...iSys,
          id: '4sKV5BdioRnVsrob4eKLDB',
        },
        __typename: 'MenuItem',
        internalName: 'Dummy Header - Languages',
        label: 'Languages',
        description: null,
        link: null,
        image: null,
        button: null,
        blogFormat: null,
        menuCollection: {
          total: 0,
          limit: 0,
          skip: 0,
          items: [
            {
              ...iAsset,
              sys: {
                ...iSys,
                id: '6VbOUcliVbF1XDiZ0VsLpH',
              },
              __typename: 'MenuItem',
              internalName: 'Dummy Header - Languages - English',
              label: 'English',
              description: 'en',
              link: 'https://www.freshworks.com',
              image: null,
              button: null,
              blogFormat: null,
              menuCollection: {
                total: 0,
                limit: 0,
                skip: 0,
                items: [],
              },
            },
            {
              ...iAsset,
              sys: {
                ...iSys,
                id: '6QRIsrZAylFrbshwdWjMQ8',
              },
              __typename: 'MenuItem',
              internalName: 'Dummy Header - Languages - Spanish',
              label: 'Spanish',
              description: 'es',
              link: 'https://www.freshworks.com',
              image: null,
              button: null,
              blogFormat: null,
              menuCollection: {
                total: 0,
                limit: 0,
                skip: 0,
                items: [],
              },
            },
          ],
        },
      },
      {
        sys: {
          ...iSys,
          id: '6kHI9RjJGpewVdneXsPDQt',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header - Login',
        label: 'Login',
        description: null,
        link: 'https://www.freshworks.com/',
        image: null,
        button: null,
        menuCollection: {
          total: 0,
          limit: 0,
          skip: 0,
          items: [],
        },
      },
    ],
  },
};
