import { ComponentStory } from '@storybook/react';

import { iAsset, iSys } from 'assets/mockData/emptyTypes';

import ComponentHeaderProduct from 'components/HeaderProduct/Header';

const Template: ComponentStory<typeof ComponentHeaderProduct> = args => <ComponentHeaderProduct {...args} />;

export const componentHeaderProduct = Template.bind({});

componentHeaderProduct.parameters = {
  controls: {
    include: [],
  },
};

componentHeaderProduct.args = {
  __typename: 'ComponentHeader',
  headerStyle: 'Product Nav',
  internalName: 'Dummy Component Header - Product Nav - Freshdesk',
  callToAction: {
    sys: {
      ...iSys,
      id: '3kNy8c8HIcUbKiNbqQneLq',
    },
    ...iAsset,
    __typename: 'ComponentButton',
    internalName: 'Dummy Button - Header- CTA - Light',
    label: 'Free trial',
    labelIcon: null,
    link: 'https://www.freshworks.com/',
    hierarchy: 'Tertiary Gray',
    size: 'Large',
    startIcon: null,
    endIcon: null,
    rainbowHover: true,
  },
  callToActionDark: {
    sys: {
      ...iSys,
      id: '31vsTV0zVNWc992aDlHw2U',
    },
    ...iAsset,
    __typename: 'ComponentButton',
    internalName: 'Dummy Button - Header- CTA - Dark',
    label: 'Free trial',
    labelIcon: null,
    link: 'https://www.freshworks.com/',
    hierarchy: 'Dark Outline',
    size: 'Large',
    startIcon: null,
    endIcon: null,
    rainbowHover: true,
  },
  callToActionMobile: {
    sys: {
      ...iSys,
      id: '6kHI9RjJGpewVdneXsPDQt',
    },
    ...iAsset,
    __typename: 'ComponentButton',
    internalName: 'Dummy Button Primary',
    label: 'Start free trial',
    labelIcon: null,
    link: 'https://freshworks.com/',
    hierarchy: 'Primary Color',
    size: 'XLarge',
    startIcon: null,
    endIcon: null,
    rainbowHover: null,
  },
  navigationLinksCollection: {
    limit: 0,
    skip: 0,
    total: 0,
    items: [
      {
        sys: {
          ...iSys,
          id: '4zTcQYuZAtEdx6Wn1OQ0ZZ',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Freshdesk - Main',
        label: 'Freshdesk',
        description: null,
        link: null,
        image: null,
        button: null,
        blogFormat: false,
        menuCollection: {
          limit: 0,
          skip: 0,
          total: 0,
          items: [
            {
              sys: {
                ...iSys,
                id: '15jotTTMIDKzwE8tHhwryZ',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Freshdesk',
              label: 'Freshdesk products',
              description: null,
              link: null,
              image: null,
              button: null,
              blogFormat: null,
              menuCollection: {
                limit: 0,
                skip: 0,
                total: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '1QdFNiU6fWKjXcyjsnt7Ou',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Omnichannel suite ',
                    label: 'Omnichannel suite',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://freshdesk.com/',
                    blogFormat: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '7gi0pxWrpSjHDLKhjVpRzS',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Support desk',
                    label: 'Support desk',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://freshdesk.com/',
                    blogFormat: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '4JOG3LuZ5OCNjOnb76c6no',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Contact center',
                    label: 'Contact center',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://freshdesk.com/',
                    blogFormat: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6p0lNGJ85zJmtfLnUPS9t2',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Messaging',
                    label: 'Messaging',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://freshdesk.com/',
                    blogFormat: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '76vJk7FGgmLLDN8786FL4L',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Customer success',
                    label: 'Customer success',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://freshdesk.com/',
                    blogFormat: null,
                    image: null,
                    button: null,
                  },
                ],
              },
            },
            {
              sys: {
                ...iSys,
                id: 'fWe8VRR6ku0cpX6RnvqbD',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Product Releases',
              label: 'Product Releases',
              description: null,
              link: null,
              image: null,
              button: null,
              blogFormat: null,
              menuCollection: {
                limit: 0,
                skip: 0,
                total: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '3wUoqskqm3kdFyxpUhIIfW',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Product Release Item 1',
                    label: 'Lorem ipsum dolor sit amet',
                    description: 'An end-to-end, AI powered enterprise platform to unify customer experiences',
                    link: 'https://freshdesk.com/',
                    blogFormat: null,
                    image: {
                      sys: {
                        ...iSys,
                        id: '7h6uJCDTBe0Ud7iSA0d28c',
                      },
                      ...iAsset,
                      __typename: 'ComponentImage',
                      internalName: 'Dummy Product Release Image 1',
                      title: 'Dummy Product Release Image 1',
                      image: {
                        sys: {
                          ...iSys,
                          id: '5KL9SCs2VG0secn1kfev3S',
                        },
                        ...iAsset,
                        __typename: 'Asset',
                        contentType: 'image/png',
                        title: 'Dummy Product Release Item 1',
                        description: 'For Dummy use Freshdesk Product Release Item 1 ',
                        url: 'https://images.ctfassets.net/bmpbi2fhxoeu/5KL9SCs2VG0secn1kfev3S/fd8ced97ccc0104c94198713f69c75b9/Image.png',
                        width: 233,
                        height: 161,
                      },
                    },
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: 'G0HIZUcZ32VvbVcJXFGzp',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Product Release Item 2',
                    label: 'Lorem ipsum dolor sit amet',
                    description: 'An end-to-end, AI powered enterprise platform to unify customer experiences',
                    link: 'https://freshdesk.com/',
                    blogFormat: null,
                    image: {
                      sys: {
                        ...iSys,
                        id: '5oS7t1OTGsCaSdH1mbH24P',
                      },
                      ...iAsset,
                      __typename: 'ComponentImage',
                      internalName: 'Dummy Product Release Image 2',
                      title: 'Dummy Product Release Image 2',
                      image: {
                        sys: {
                          ...iSys,
                          id: '1C4UFFmBpK95aej3iWwbaM',
                        },
                        ...iAsset,
                        __typename: 'Asset',
                        contentType: 'image/png',
                        title: 'Dummy Product Release Image 2',
                        description: 'for freshdesk dummy Product Release Image 2',
                        url: 'https://images.ctfassets.net/bmpbi2fhxoeu/1C4UFFmBpK95aej3iWwbaM/b7d03f3ecc9ac3a225bdd14963db295b/Image.png',
                        width: 233,
                        height: 161,
                      },
                    },
                    button: null,
                  },
                ],
              },
            },
          ],
        },
      },
      {
        sys: {
          ...iSys,
          id: '3i0Vw2i5Bp22R5LzENdHA9',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header - Features',
        label: 'Features ',
        description: null,
        link: 'https://www.freshworks.com/',
        image: null,
        button: null,
        blogFormat: false,
        menuCollection: {
          limit: 0,
          skip: 0,
          total: 0,
          items: [],
        },
      },
      {
        sys: {
          ...iSys,
          id: '4OYCy3RSYGNMvPtu9VsiAl',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header - Pricing',
        label: 'Pricing',
        description: null,
        link: 'https://www.freshworks.com/',
        image: null,
        button: null,
        blogFormat: null,
        menuCollection: {
          limit: 0,
          skip: 0,
          total: 0,
          items: [],
        },
      },
      {
        sys: {
          ...iSys,
          id: '2EqSBnBgO8O6EyKq6WWtX8',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header Solutions',
        label: 'Solutions',
        description: null,
        link: null,
        image: null,
        button: null,
        blogFormat: false,
        menuCollection: {
          limit: 0,
          skip: 0,
          total: 0,
          items: [
            {
              sys: {
                ...iSys,
                id: '1ERyRlWndN4Z019Pmt1iLY',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header Solutions - By Size',
              label: 'By size',
              description: null,
              link: null,
              image: null,
              button: null,
              blogFormat: false,
              menuCollection: {
                limit: 0,
                skip: 0,
                total: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '7qWhKszNtDYPj6bf9iTurW',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Size - Enterprise',
                    label: 'Enterprise',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '3IiIhy4hkutTAZcW14o22f',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Size - SMB',
                    label: 'SMB',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                ],
              },
            },
            {
              sys: {
                ...iSys,
                id: '69fbB9v30rkpdhAOh6CKFf',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header Solutions - By Use Case',
              label: 'By use case',
              description: null,
              link: null,
              image: null,
              button: null,
              blogFormat: false,
              menuCollection: {
                limit: 0,
                skip: 0,
                total: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '5SGsFWurTa5IbYA9jHnjKA',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Use Case - Omnichannel',
                    label: 'Omnichannel',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '4olmLCg9BetVspr3MIR9N4',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Use Case - AI',
                    label: 'AI',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6OlQDovuk3jnjeHGoF273h',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Use Case - Self service',
                    label: 'Self service',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6jiRITCEvmne3dzW4AoEpo',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Use Case - Field service',
                    label: 'Field service',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                ],
              },
            },
            {
              sys: {
                ...iSys,
                id: '5IVobJy6H19sbO0CIEXGqK',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header Solutions - By Industry',
              label: 'By industry',
              description: null,
              link: null,
              image: null,
              button: null,
              blogFormat: false,
              menuCollection: {
                limit: 0,
                skip: 0,
                total: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '2lVdz0B50253P8LZiNCdrz',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Industry - Retail & e-commerce',
                    label: 'Retail & e-commerce',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '4hKLqlYsKUIDrJP6AcqE6P',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Industry - Travel & hospitality',
                    label: 'Travel & hospitality',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: 'TY6o6oEW0cICz4gO264F1',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Industry - Software & IT',
                    label: 'Software & IT',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                ],
              },
            },
          ],
        },
      },
      {
        sys: {
          ...iSys,
          id: '4sKV5BdioRnVsrob4eKLDB',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header - Languages',
        label: 'Languages',
        description: null,
        link: null,
        image: null,
        button: null,
        blogFormat: null,
        menuCollection: {
          limit: 0,
          skip: 0,
          total: 0,
          items: [
            {
              sys: {
                ...iSys,
                id: '6VbOUcliVbF1XDiZ0VsLpH',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header - Languages - English',
              label: 'English',
              description: 'en',
              link: 'https://www.freshworks.com',
              image: null,
              button: null,
              blogFormat: null,
              menuCollection: {
                limit: 0,
                skip: 0,
                total: 0,
                items: [],
              },
            },
            {
              sys: {
                ...iSys,
                id: '6QRIsrZAylFrbshwdWjMQ8',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header - Languages - Spanish',
              label: 'Spanish',
              description: 'es',
              link: 'https://www.freshworks.com',
              image: null,
              button: null,
              blogFormat: null,
              menuCollection: {
                limit: 0,
                skip: 0,
                total: 0,
                items: [],
              },
            },
          ],
        },
      },
      {
        sys: {
          ...iSys,
          id: 'ztjV7mcwAqSKXbUI49Frj',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header - Login',
        label: 'Login',
        description: null,
        link: 'https://www.freshworks.com/',
        image: null,
        button: null,
        blogFormat: null,
        menuCollection: {
          limit: 0,
          skip: 0,
          total: 0,
          items: [],
        },
      },
      {
        sys: {
          ...iSys,
          id: '4YqK2gJiUpBTz9WONbZPY',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header - All Products',
        label: 'All Products',
        description: null,
        link: null,
        image: null,
        button: null,
        blogFormat: false,
        menuCollection: {
          limit: 0,
          skip: 0,
          total: 0,
          items: [],
        },
      },
    ],
  },
  navigationLinksMobileCollection: {
    limit: 0,
    skip: 0,
    total: 0,
    items: [
      {
        sys: {
          ...iSys,
          id: 'ai9gZTLlIkhRPH8g4yRZv',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header Products - Mobile',
        label: 'Products',
        description: null,
        link: null,
        image: null,
        button: null,
        blogFormat: false,
        menuCollection: {
          limit: 0,
          skip: 0,
          total: 0,
          items: [
            {
              sys: {
                ...iSys,
                id: '6q5SVyw4JePsXuraESKPpH',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header Products - Software - Mobile',
              label: 'Software',
              description: null,
              link: null,
              image: null,
              button: {
                sys: {
                  ...iSys,
                  id: '67mx29SJrbyhogN1bQM7N4',
                },
                ...iAsset,
                __typename: 'ComponentButton',
                internalName: 'Dummy Header - View all Products',
                label: 'View all products',
                labelIcon: null,
                link: 'https://www.freshworks.com/',
                hierarchy: 'Link Color',
                size: 'Large',
                startIcon: null,
                endIcon: '>',
                rainbowHover: false,
              },
              blogFormat: false,
              menuCollection: {
                limit: 0,
                skip: 0,
                total: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '7ybnO32p98JzH91GNR9Isd',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Software - Freshdesk - Mobile',
                    label: 'Freshdesk',
                    description: 'Customer support software',
                    link: 'https://www.freshworks.com/',
                    blogFormat: false,
                    image: null,
                    button: null,
                    menuCollection: {
                      limit: 0,
                      skip: 0,
                      total: 0,
                      items: [
                        {
                          sys: {
                            ...iSys,
                            id: '1QdFNiU6fWKjXcyjsnt7Ou',
                          },
                          ...iAsset,
                          internalName: 'Dummy Omnichannel suite ',
                          label: 'Omnichannel suite',
                          description: 'Lorem ipsum dolor sit amet',
                          link: 'https://freshdesk.com/',
                          blogFormat: false,
                        },
                        {
                          sys: {
                            ...iSys,
                            id: '7gi0pxWrpSjHDLKhjVpRzS',
                          },
                          ...iAsset,
                          internalName: 'Dummy Support desk',
                          label: 'Support desk',
                          description: 'Lorem ipsum dolor sit amet',
                          link: 'https://freshdesk.com/',
                          blogFormat: false,
                        },
                        {
                          sys: {
                            ...iSys,
                            id: '4JOG3LuZ5OCNjOnb76c6no',
                          },
                          ...iAsset,
                          internalName: 'Dummy Contact center',
                          label: 'Contact center',
                          description: 'Lorem ipsum dolor sit amet',
                          link: 'https://freshdesk.com/',
                          blogFormat: false,
                        },
                        {
                          sys: {
                            ...iSys,
                            id: '6p0lNGJ85zJmtfLnUPS9t2',
                          },
                          ...iAsset,
                          internalName: 'Dummy Messaging',
                          label: 'Messaging',
                          description: 'Lorem ipsum dolor sit amet',
                          link: 'https://freshdesk.com/',
                          blogFormat: false,
                        },
                        {
                          sys: {
                            ...iSys,
                            id: '76vJk7FGgmLLDN8786FL4L',
                          },
                          ...iAsset,
                          internalName: 'Dummy Customer success',
                          label: 'Customer success',
                          description: 'Lorem ipsum dolor sit amet',
                          link: 'https://freshdesk.com/',
                          blogFormat: false,
                        },
                      ],
                    },
                  },
                  {
                    sys: {
                      ...iSys,
                      id: 'TdRUP5bjiutxO743Or5DD',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Software - Freshsales - Mobile',
                    label: 'Freshsales',
                    description: 'Sales CRM Software',
                    link: 'https://www.freshworks.com/',
                    blogFormat: false,
                    image: null,
                    button: null,
                    menuCollection: {
                      limit: 0,
                      skip: 0,
                      total: 0,
                      items: [
                        {
                          sys: {
                            ...iSys,
                            id: '1QdFNiU6fWKjXcyjsnt7Ou',
                          },
                          ...iAsset,
                          internalName: 'Dummy Omnichannel suite ',
                          label: 'Omnichannel suite',
                          description: 'Lorem ipsum dolor sit amet',
                          link: 'https://freshdesk.com/',
                          blogFormat: false,
                        },
                        {
                          sys: {
                            ...iSys,
                            id: '7gi0pxWrpSjHDLKhjVpRzS',
                          },
                          ...iAsset,
                          internalName: 'Dummy Support desk',
                          label: 'Support desk',
                          description: 'Lorem ipsum dolor sit amet',
                          link: 'https://freshdesk.com/',
                          blogFormat: false,
                        },
                      ],
                    },
                  },
                  {
                    sys: {
                      ...iSys,
                      id: 'ptUCPbtPT9GXeBS9F6KUo',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Software - Freshmarketer - Mobile',
                    label: 'Freshmarketer',
                    description: 'Conversion Optimization Suite',
                    link: 'https://www.freshworks.com/',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '4HMjH4yfgescIT014xkjmp',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Software - Freshteam - Mobile',
                    label: 'Freshteam',
                    description: 'HR Software for growing business',
                    link: 'https://www.freshworks.com/',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '1bX95bRENaL4WihRk1ZKUD',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Software - Freshservice - Mobile',
                    label: 'Freshservice',
                    description: 'IT service management software',
                    link: 'https://www.freshworks.com/',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                ],
              },
            },
            {
              sys: {
                ...iSys,
                id: 'fWe8VRR6ku0cpX6RnvqbD',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Product Releases',
              label: 'Product Releases',
              description: null,
              link: null,
              image: null,
              button: null,
              blogFormat: false,
              menuCollection: {
                limit: 0,
                skip: 0,
                total: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '3wUoqskqm3kdFyxpUhIIfW',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Product Release Item 1',
                    label: 'Lorem ipsum dolor sit amet',
                    description: 'An end-to-end, AI powered enterprise platform to unify customer experiences',
                    link: 'https://freshdesk.com/',
                    blogFormat: false,
                    image: {
                      sys: {
                        ...iSys,
                        id: '7h6uJCDTBe0Ud7iSA0d28c',
                      },
                      ...iAsset,
                      __typename: 'ComponentImage',
                      internalName: 'Dummy Product Release Image 1',
                      title: 'Dummy Product Release Image 1',
                      image: {
                        sys: {
                          ...iSys,
                          id: '5KL9SCs2VG0secn1kfev3S',
                        },
                        ...iAsset,
                        __typename: 'Asset',
                        contentType: 'image/png',
                        title: 'Dummy Product Release Item 1',
                        description: 'For Dummy use Freshdesk Product Release Item 1 ',
                        url: 'https://images.ctfassets.net/bmpbi2fhxoeu/5KL9SCs2VG0secn1kfev3S/fd8ced97ccc0104c94198713f69c75b9/Image.png',
                        width: 233,
                        height: 161,
                      },
                    },
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: 'G0HIZUcZ32VvbVcJXFGzp',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Product Release Item 2',
                    label: 'Lorem ipsum dolor sit amet',
                    description: 'An end-to-end, AI powered enterprise platform to unify customer experiences',
                    link: 'https://freshdesk.com/',
                    blogFormat: false,
                    image: {
                      sys: {
                        ...iSys,
                        id: '5oS7t1OTGsCaSdH1mbH24P',
                      },
                      ...iAsset,
                      __typename: 'ComponentImage',
                      internalName: 'Dummy Product Release Image 2',
                      title: 'Dummy Product Release Image 2',
                      image: {
                        sys: {
                          ...iSys,
                          id: '1C4UFFmBpK95aej3iWwbaM',
                        },
                        ...iAsset,
                        __typename: 'Asset',
                        contentType: 'image/png',
                        title: 'Dummy Product Release Image 2',
                        description: 'for freshdesk dummy Product Release Image 2',
                        url: 'https://images.ctfassets.net/bmpbi2fhxoeu/1C4UFFmBpK95aej3iWwbaM/b7d03f3ecc9ac3a225bdd14963db295b/Image.png',
                        width: 233,
                        height: 161,
                      },
                    },
                    button: null,
                  },
                ],
              },
            },
            {
              sys: {
                ...iSys,
                id: '1fPb5qR3dNn6JTmYWkV40e',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header - Products - Solutions',
              label: 'Solutions',
              description: null,
              link: null,
              image: null,
              button: null,
              blogFormat: null,
              menuCollection: {
                limit: 0,
                skip: 0,
                total: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '4wpWENc2GCN6KSvrdYc3BB',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Solutions - Enterprise',
                    label: 'Enterprise service management',
                    description: null,
                    link: 'https://www.freshworks.com/',
                    blogFormat: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6mtRsliICvG049ZLhOHWEq',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Solutions - Industry',
                    label: 'Industry solutions',
                    description: null,
                    link: 'https://www.freshworks.com/',
                    blogFormat: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '2njBqKJbPZpYdPiKOsc6Gb',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Solutions - Direct',
                    label: 'Direct-to-consumer e-commerce',
                    description: null,
                    link: 'https://www.freshworks.com/',
                    blogFormat: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6f0gSFgORULXlXp4wrGNxG',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Solutions - Conversational',
                    label: 'Conversational engagement',
                    description: null,
                    link: 'https://www.freshworks.com/',
                    blogFormat: null,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '3iDzK9B88wN01z1SMJpFF4',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header - Products - Solutions - Customer relationship Management',
                    label: 'Customer Relationship Management',
                    description: null,
                    link: 'https://www.freshworks.com/',
                    blogFormat: null,
                    image: null,
                    button: null,
                  },
                ],
              },
            },
          ],
        },
      },
      {
        sys: {
          ...iSys,
          id: '3i0Vw2i5Bp22R5LzENdHA9',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header - Features',
        label: 'Features ',
        description: null,
        link: 'https://www.freshworks.com/',
        image: null,
        button: null,
        blogFormat: false,
        menuCollection: {
          limit: 0,
          skip: 0,
          total: 0,
          items: [],
        },
      },
      {
        sys: {
          ...iSys,
          id: '4OYCy3RSYGNMvPtu9VsiAl',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header - Pricing',
        label: 'Pricing',
        description: null,
        link: 'https://www.freshworks.com/',
        image: null,
        button: null,
        blogFormat: null,
        menuCollection: {
          limit: 0,
          skip: 0,
          total: 0,
          items: [],
        },
      },
      {
        sys: {
          ...iSys,
          id: '2lcl4kh5pJCYA6UyksWJ0G',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header Solutions - Mobile with Child Menu',
        label: 'Solutions',
        description: null,
        link: null,
        image: null,
        button: null,
        blogFormat: false,
        menuCollection: {
          limit: 0,
          skip: 0,
          total: 0,
          items: [
            {
              sys: {
                ...iSys,
                id: '1ERyRlWndN4Z019Pmt1iLY',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header Solutions - By Size',
              label: 'By Size',
              description: null,
              link: null,
              image: null,
              button: null,
              blogFormat: false,
              menuCollection: {
                limit: 0,
                skip: 0,
                total: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '7qWhKszNtDYPj6bf9iTurW',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Size - Enterprise',
                    label: 'Enterprise',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '3IiIhy4hkutTAZcW14o22f',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Size - SMB',
                    label: 'SMB',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                ],
              },
            },
            {
              sys: {
                ...iSys,
                id: '69fbB9v30rkpdhAOh6CKFf',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header Solutions - By Use Case',
              label: 'By Use Case',
              description: null,
              link: null,
              image: null,
              button: null,
              blogFormat: false,
              menuCollection: {
                limit: 0,
                skip: 0,
                total: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '5SGsFWurTa5IbYA9jHnjKA',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Use Case - Omnichannel',
                    label: 'Omnichannel',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '4olmLCg9BetVspr3MIR9N4',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Use Case - AI',
                    label: 'AI',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6OlQDovuk3jnjeHGoF273h',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Use Case - Self service',
                    label: 'Self service',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '6jiRITCEvmne3dzW4AoEpo',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Use Case - Field service',
                    label: 'Field service',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                ],
              },
            },
            {
              sys: {
                ...iSys,
                id: '5IVobJy6H19sbO0CIEXGqK',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header Solutions - By Industry',
              label: null,
              description: null,
              link: null,
              image: null,
              button: null,
              blogFormat: false,
              menuCollection: {
                limit: 0,
                skip: 0,
                total: 0,
                items: [
                  {
                    sys: {
                      ...iSys,
                      id: '2lVdz0B50253P8LZiNCdrz',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Industry - Retail & e-commerce',
                    label: 'Retail & e-commerce',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: '4hKLqlYsKUIDrJP6AcqE6P',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Industry - Travel & hospitality',
                    label: 'Travel & hospitality',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                  {
                    sys: {
                      ...iSys,
                      id: 'TY6o6oEW0cICz4gO264F1',
                    },
                    ...iAsset,
                    __typename: 'MenuItem',
                    internalName: 'Dummy Header Solutions - By Industry - Software & IT',
                    label: 'Software & IT',
                    description: 'Lorem ipsum dolor sit amet',
                    link: 'https://www.freshworks.com',
                    blogFormat: false,
                    image: null,
                    button: null,
                  },
                ],
              },
            },
          ],
        },
      },
      {
        sys: {
          ...iSys,
          id: '4sKV5BdioRnVsrob4eKLDB',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header - Languages',
        label: 'Languages',
        description: null,
        link: null,
        image: null,
        button: null,
        blogFormat: null,
        menuCollection: {
          limit: 0,
          skip: 0,
          total: 0,
          items: [
            {
              sys: {
                ...iSys,
                id: '6VbOUcliVbF1XDiZ0VsLpH',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header - Languages - English',
              label: 'English',
              description: 'en',
              link: 'https://www.freshworks.com',
              image: null,
              button: null,
              blogFormat: null,
              menuCollection: {
                limit: 0,
                skip: 0,
                total: 0,
                items: [],
              },
            },
            {
              sys: {
                ...iSys,
                id: '6QRIsrZAylFrbshwdWjMQ8',
              },
              ...iAsset,
              __typename: 'MenuItem',
              internalName: 'Dummy Header - Languages - Spanish',
              label: 'Spanish',
              description: 'es',
              link: 'https://www.freshworks.com',
              image: null,
              button: null,
              blogFormat: null,
              menuCollection: {
                limit: 0,
                skip: 0,
                total: 0,
                items: [],
              },
            },
          ],
        },
      },
      {
        sys: {
          ...iSys,
          id: 'ztjV7mcwAqSKXbUI49Frj',
        },
        ...iAsset,
        __typename: 'MenuItem',
        internalName: 'Dummy Header - Login',
        label: 'Login',
        description: null,
        link: 'https://www.freshworks.com/',
        image: null,
        button: null,
        blogFormat: null,
        menuCollection: {
          limit: 0,
          skip: 0,
          total: 0,
          items: [],
        },
      },
    ],
  },
};
